# Generated by Django 3.2.9 on 2021-11-15 16:16

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pics', models.ImageField(default='avatar.png', upload_to='profile-images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'], message='File can only be image type')])),
                ('company', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(11, message='phone can only have 11 digits')])),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='owner', unique_with=['created', 'address', 'company'])),
                ('about', models.TextField()),
                ('twitter', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
