# Generated by Django 3.2.9 on 2021-11-15 16:24

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211115_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='owner', unique_with=['created', 'address', 'company']),
        ),
    ]
