# Generated by Django 3.2.9 on 2021-11-15 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211115_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxLengthValidator(11, message='phone can only have 11 digits')]),
        ),
    ]
