# Generated by Django 3.2.9 on 2021-11-16 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20211115_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pics',
            new_name='avatar',
        ),
    ]
