# Generated by Django 3.2.9 on 2021-11-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_alter_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
