# Generated by Django 3.2.9 on 2021-11-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(default='eat outside'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Feeding', 'Feeding'), ('Schooling', 'Schooling')], max_length=255),
        ),
    ]
