# Generated by Django 3.2.9 on 2021-11-20 10:18

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expensecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='name', unique_with=['created']),
            preserve_default=False,
        ),
    ]
