# Generated by Django 3.2.9 on 2021-11-20 13:19

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0003_expensecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='description', unique_with=['owner', 'category', 'created', 'updated']),
        ),
    ]
