# Generated by Django 3.2.9 on 2021-11-20 14:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20211120_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['owner', 'created']),
        ),
    ]
