# Generated by Django 3.2.9 on 2021-11-14 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20211114_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
