# Generated by Django 3.2.9 on 2021-11-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_category_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
    ]
