# Generated by Django 3.2.9 on 2021-11-15 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_remove_category_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ExpenseCategory',
        ),
    ]
