# Generated by Django 3.2.9 on 2021-11-15 12:49

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Income Source',
                'verbose_name_plural': 'Income Source',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=800)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='description', unique_with=['income_date', 'amount', 'category', 'created'])),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0, message="sorry your expenses can't be less than zero")])),
                ('income_date', models.DateField(help_text='yyyy-mm-dd')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.source')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
