# Generated by Django 3.2.9 on 2021-11-20 10:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_alter_income_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['created']),
        ),
    ]
