# Generated by Django 3.2.9 on 2021-11-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_source_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-created'], 'verbose_name': 'Income Source', 'verbose_name_plural': 'Income Source'},
        ),
    ]
